### ISSUE TITLE
Playing audio from UrlSource causes Exception on Android Emulator.

### ISSUE THREAD

**Issue by Tobi696** [bluefireteam/audioplayers#1250]
Playing remote audio (https://api.whatda.fit/sample-audios/MP%20Clapping%20Crunches%2045.mp3) causes Android Exception.

## Current bug behaviour
Exception:
```
V/MediaPlayer(18296): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18296): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(18296): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18296): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(18296): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(18296): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService(18296): MediaHTTPService(android.media.MediaHTTPService@1d86dac): Cookies: null
V/MediaHTTPService(18296): makeHTTPConnection: CookieHandler (java.net.CookieManager@3104e09) exists.
V/MediaHTTPService(18296): makeHTTPConnection(android.media.MediaHTTPService@1d86dac): cookieHandler: java.net.CookieManager@3104e09 Cookies: null
E/MediaPlayerNative(18296): pause called in state 4, mPlayer(0xbaff4ed0)
E/MediaPlayerNative(18296): error (-38, 0)
E/MediaPlayer(18296): Error (-38,0)
E/flutter (18296): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MediaPlayer error with what:MEDIA_ERROR_UNKNOWN {what:-38} extra:MEDIA_ERROR_UNKNOWN {extra:0}
```

## Expected behaviour
The audio should be played.

## Steps to reproduce
```
await _audioPlayer.play(UrlSource('https://api.whatda.fit/sample-audios/MP%20Clapping%20Crunches%2045.mp3'));
await _audioPlayer.pause();
```

Flutter 3.0.5, Android Emulator

On an iOS Simulator it works.

**Comment by larssn** [comment]
It happens in production for us. Typically when you use overlapping audio, so if you have a sound hooked up to a button, and then spam that button, the exception will happen.

**Comment by Tobi696** [comment]
This exception also causes onPlayerComplete to fire.

**Comment by Gustl22** [comment]
@Tobi696 can you test with current `main` in pubspec.yaml? Or test your link inside [example](https://github.com/bluefireteam/audioplayers/blob/6fad1cc4443e623e5c94519f130b4004b2dc3857/packages/audioplayers/example/lib/tabs/sources.dart#L9) project?
```
dependencies:
  audioplayers:
    git: 
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
```

I tried it also with previous commits and it played flawlessly.

**Comment by Tobi696** [comment]
@Gustl22 The problem was that my code looked like this:
```
await audioPlayer.play(...);
await audioPlayer.pause();
```
Basically, I wanted the audioplayer to download the mp3 in advance, but not play it instantly, so I called pause() instantly after play(). That is what caused the error on Android.

**Comment by Gustl22** [comment]
@Tobi696 can you test with current `main`? I think it is fixed there.

**Comment by Tobi696** [comment]
Unfortunately, I still get the same issue, here you have my full widget:
```dart
import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart' as $ap;

class AudioPlayer extends StatefulWidget {
  final String audioUrl;

  const AudioPlayer({Key? key, required this.audioUrl}) : super(key: key);

  @override
  State<AudioPlayer> createState() => _AudioPlayerState();
}

class _AudioPlayerState extends State<AudioPlayer> {
  final _audioPlayer = $ap.AudioPlayer();

  @override
  void initState() {
    super.initState();
    loadAudio();
  }

  Future<void> loadAudio() async {
    await _audioPlayer.play($ap.UrlSource(widget.audioUrl));
    await _audioPlayer.pause();
  }

  @override
  void dispose() {
    _audioPlayer.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return const SizedBox();
  }
}
```
Just use it in a scaffold's body and pass 'https://api.whatda.fit/sample-audios/MP%20Clapping%20Crunches%2045.mp3' as audioUrl.

**Comment by Gustl22** [comment]
Sorry I forgot to mention you also have to override the android dependency:

```
dependency_overrides: 
  audioplayers_android:
    git: 
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_android'
```

**Comment by Gustl22** [comment]
Also you cannot play audio without context within `initState`.

Wrap your code to be executed, when build was executed:

```
void initState() {
    super.initState();
    WidgetsBinding.instance!.addPostFrameCallback((_) {
        loadAudio();
    })
  }
```

**Comment by Tobi696** [comment]
The combination of using the dependency override and addPostFrameCallback() made it work for me.
Thank you a lot!
